package com.github.israelermel.iridio77.models

enum class AndroidDebugEvent {
    SHOW_LAYOUT_BOUNDS,
    TOOGLE_TALKBACK,
    TOOGLE_ANIMATIONS,
    TOOGLE_PROFILE,
    TOOGLE_OVERDRAW,
    RESET_CONFIGURATION,
    TOOGLE_COLOR_INVERSION,
    TOOGLE_SCREEN_TOUCHES,
}